### ISSUE TITLE
code review for portolio

### ISSUE THREAD

**Issue by ghermaico135** [sahlminkok/Portfolio#7]
Duplicate nav tags,so why shouldn't use one nav tag and use list menu?
why you shouldn't use proper semantics ? Because it gives more clarity and professional way of organizing the code.

**Comment by ghermaico135** [comment]
Why shouldn't try to manipulate the menu with one nav tag,instead using so many times?This reduce code clarity

**Comment by efmomoh** [comment]
I think you can put all the <a> anchor tags in an unorder-list
This help for navigation purposes that is putting all links in one unorder-list (ul) tag per section...
